services:
  - type: web
    name: buxoro-maktabi
    repo: https://github.com/hackzirov-sketch/Buxoro_Maktab
    branch: main
    buildCommand: npm install -g pnpm@10.26.1 && pnpm install && pnpm --filter @workspace/buxoro-maktabi run build && cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
